// Created by TraceCompiler 2.2.3
// DO NOT EDIT, CHANGES WILL BE LOST

#ifndef __HARVESTERSERVERSESSIONTRACES_H__
#define __HARVESTERSERVERSESSIONTRACES_H__

#define KOstTraceComponentID 0x200009f5

#define CHARVESTERSERVERSESSION_NEWL 0x8600bd
#define CHARVESTERSERVERSESSION_NEWLC 0x8600be
#define CHARVESTERSERVERSESSION_CONSTRUCTL 0x8600bf
#define CHARVESTERSERVERSESSION_CHARVESTERSERVERSESSION 0x8600c0
#define DUP1_CHARVESTERSERVERSESSION_CHARVESTERSERVERSESSION 0x8600c1
#define CHARVESTERSERVERSESSION_SERVICEL 0x8600c2
#define CHARVESTERSERVERSESSION_DISCONNECT 0x8600c3


#endif

// End of file

